services:
  
  frontend:
    image: node:20
    container_name: lineage-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    depends_on:
      api:
        condition: service_started
  
  postgres:
    image: postgres:16
    container_name: lineage-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lineage_user -d lineage"]
      interval: 5s
      timeout: 5s
      retries: 5

  parser:
    build:
      context: .
      dockerfile: ./parser/Dockerfile
    container_name: lineage-parser
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: no

  api:
    build: ./api
    container_name: lineage-api
    ports:
      - "3000:3000"
    environment:
      - GRAPH_URL=http://graph:7373
#    depends_on:
#      postgres:
#        condition: service_healthy
#      graph:
#        condition: service_started

  graph:
    build:
      context: .
      dockerfile: ./graphworker/Dockerfile
    container_name: graph-worker
    env_file:
      - .env
#    depends_on:
#      parser:
#        condition: service_completed_successfully
    ports:
      - "7373:7373"
  

volumes:
  pgdata:

